#!/usr/bin/env bash
# Interactively generate operator.yml from callsign + Maidenhead grid square.
# operator.yml is gitignored and never committed to the repo.
set -euo pipefail

OUT="$(cd "$(dirname "$0")" && pwd)/operator.yml"

echo "=== Satellite station operator setup ==="
echo

read -rp "Callsign: " callsign
read -rp "Maidenhead grid square (6 chars, e.g. DM03sw): " grid
read -rp "Location description (e.g. El Segundo, CA): " location
read -rp "Altitude in metres (e.g. 10): " alt

coords=$(python3 - "$grid" << 'PY'
import sys
g = sys.argv[1]
if len(g) < 6:
    print("ERROR: need a 6-character grid square", file=sys.stderr)
    sys.exit(1)
lon  = (ord(g[0].upper()) - ord('A')) * 20 - 180
lat  = (ord(g[1].upper()) - ord('A')) * 10 - 90
lon += int(g[2]) * 2
lat += int(g[3]) * 1
lon += (ord(g[4].lower()) - ord('a')) * (5/60)
lat += (ord(g[5].lower()) - ord('a')) * (2.5/60)
# Centre of subsquare
lon += (5/60) / 2
lat += (2.5/60) / 2
print(f"{lat:.4f} {lon:.4f}")
PY
)

lat=$(echo "$coords" | awk '{print $1}')
lon=$(echo "$coords" | awk '{print $2}')

cat > "$OUT" << YAML
---
# Generated by setup-operator.sh — do not commit.

operator_callsign: "${callsign}"
operator_gridsquare: "${grid}"
operator_location: "${location}"
operator_lat: ${lat}
operator_lon: ${lon}
operator_alt_m: ${alt}
YAML

echo
echo "Written to $OUT"
echo "  Callsign : $callsign"
echo "  Grid     : $grid  →  lat=${lat}  lon=${lon}"
echo "  Location : $location"
echo "  Altitude : ${alt} m"
echo
echo "Run the playbook with:"
echo "  ansible-playbook -i inventory/hosts.ini site.yml -e @operator.yml"
