---
- name: Remove Gpredict desktop shortcut
  ansible.windows.win_file:
    path: 'C:\Users\Public\Desktop\Gpredict.lnk'
    state: absent

- name: Remove Gpredict install directory
  ansible.windows.win_file:
    path: "{{ gpredict_install_dir }}"
    state: absent

- name: Remove Gpredict hwconf files
  ansible.windows.win_file:
    path: "{{ ansible_env.APPDATA }}\\Gpredict\\hwconf\\{{ item }}"
    state: absent
  loop:
    - ft897.rig
    - ftx1.rig
    - rotator.rot

- name: Remove Gpredict config file
  ansible.windows.win_file:
    path: "{{ ansible_env.APPDATA }}\\Gpredict\\gpredict.cfg"
    state: absent

- name: Remove Gpredict staging files
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - 'C:\Temp\gpredict.zip'
    - 'C:\Temp\gpredict_stage'
